micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc?createDatabaseIfNotExist=true
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
